name: Create release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      sprintVersion:
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create release branch
        run: |
          git branch release-test-1
          git push
      
