name: Create release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      sprintVersion:
        description: Sprint version excluding patch, e.g. 1.245
        required: true
        type: string

jobs:
  create-release:
    if: github.ref_name == 'main'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create release branch
        env:
          SPRINT_VERSION: ${{ format('{0}{1}', inputs.sprintVersion, '.x') }}
          SPRINT_VERSION_WITH_PATCH: ${{ format('{0}{1}', inputs.sprintVersion, '.1') }}
        run: |
          [[ ${{ inputs.sprintVersion }} ]] || { echo "Required input sprintVersion not set, exiting."; exit 1; }
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git config push.autoSetupRemote true
          git checkout -b release/$SPRINT_VERSION
          sh update_version.sh
          git add .
          git commit -m "Release $SPRINT_VERSION_WITH_PATCH"
          git tag -a v$SPRINT_VERSION_WITH_PATCH -m "Release tag"
          git push --follow-tags
          
      - uses: actions/setup-go@v3
      - name: Update Go modules index
        env:
          SPRINT_VERSION_WITH_PATCH: ${{ format('{0}{1}', inputs.sprintVersion, '.1') }}
        run: GOPROXY=proxy.golang.org go list -m github.com/Kwintenvdb/go-test-repo@v$SPRINT_VERSION_WITH_PATCH
