name: Create release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      sprintVersion:
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create release branch
        env:
          SPRINT_VERSION: ${{ inputs.sprintVersion }}
        run: |
          [[ ${{ inputs.sprintVersion }} ]] || { echo "Required input sprintVersion not set, exiting."; exit 1; }
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git config push.autoSetupRemote true
          git checkout -b release/$SPRINT_VERSION
          sh update_version.sh
          git add .
          git commit -m "Release $SPRINT_VERSION"
          git tag -a v$SPRINT_VERSION -m "Release tag"
          git push --follow-tags
          
      - uses: actions/setup-go@v3
      - name: Update Go modules index
        run: GOPROXY=proxy.golang.org go list -m github.com/Kwintenvdb/go-test-repo@v${{ inputs.sprintVersion }}
